# Introduction

### Numpy
- The Python community has adopted naming conventions for commonly used modules

In [1]:
import numpy as np

In [2]:
my_list1=[1,2,3,4]
my_list2=[11,22,33,44]
my_lists=[my_list1,my_list2]

In [3]:
my_array1=np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [4]:
my_array2=np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [5]:
my_array2.shape # ask the shape of array

(2, 4)

In [6]:
my_array2.dtype #find out the data type of array

dtype('int64')

In [7]:
my_zeros_array=np.zeros(5)
my_zeros_array  # martix with zeros. Default nr of rows: 1

array([0., 0., 0., 0., 0.])

In [8]:
arr1=np.array([[1,2,3,4],[8,9,10,11]])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [9]:
arr1*2

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [10]:
arr1*3

array([[ 3,  6,  9, 12],
       [24, 27, 30, 33]])

In [11]:
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [12]:
arr= np.arange(0,11); arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[1:5]

array([1, 2, 3, 4])